export const GET_BEERS_LIST_INIT = 'APP/GET_BEER_LIST_INIT';
export const GET_BEERS_LIST_SUCCESS = 'APP/GET_BEER_LIST_SUCCESS';
export const GET_BEERS_LIST_FAIL = 'APP/GET_BEER_LIST_FAIL';
export const REMOVE_BEERS_FROM_LIST = 'APP/REMOVE_BEERS_FROM_LIST';
export const SET_CURRENT_BEER = 'APP/SET_CURRENT_BEER';
